exports.topicQueries = {
  angular: '/topicsPerWeek/angular.csv',
  backbone: '/topicsPerWeek/backbone.csv',
  bootstrap: '/topicsPerWeek./bootstrap.csv',
  d3: '/topicsPerWeek/d3.csv',
  decryption: '/topicsPerWeek/decryption.csv',
  drupal: '/topicsPerWeek/drupal.csv',
  ember: '/topicsPerWeek/ember.csv',
  encryption: '/topicsPerWeek/encryption.csv',
  famous: '/topicsPerWeek/famous.csv',
  flux: '/topicsPerWeek/flux.csv',
  jquery: '/topicsPerWeek/jquery.csv',
  json: '/topicsPerWeek/json.csv',
  kendo: '/topicsPerWeek/kendo.csv',
  meteor: '/topicsPerWeek/meteor.csv',
  mithril: '/topicsPerWeek/mithril.csv',
  node: '/topicsPerWeek/nodejs.csv',
  opengl: '/topicsPerWeek/opengl.csv',
  react: '/topicsPerWeek/react.csv',
  rust: '/topicsPerWeek/rust.csv',
  sencha: '/topicsPerWeek/sencha.csv',
  sprout: '/topicsPerWeek/sprout.csv',
  webgl: '/topicsPerWeek/webgl.csv'
};