exports.topicQueries = {
  angular: '/queries/topicsPerWeek/angular.csv',
  backbone: '/queries/topicsPerWeek/backbone.csv',
  bootstrap: '/queries/topicsPerWeek/bootstrap.csv',
  d3: '/queries/topicsPerWeek/d3.csv',
  decryption: '/queries/topicsPerWeek/decryption.csv',
  drupal: '/queries/topicsPerWeek/drupal.csv',
  ember: '/queries/topicsPerWeek/ember.csv',
  encryption: '/queries/topicsPerWeek/encryption.csv',
  famous: '/queries/topicsPerWeek/famous.csv',
  flux: '/queries/topicsPerWeek/flux.csv',
  jquery: '/queries/topicsPerWeek/jquery.csv',
  json: '/queries/topicsPerWeek/json.csv',
  kendo: '/queries/topicsPerWeek/kendo.csv',
  meteor: '/queries/topicsPerWeek/meteor.csv',
  mithril: '/queries/topicsPerWeek/mithril.csv',
  node: '/queries/topicsPerWeek/nodejs.csv',
  opengl: '/queries/topicsPerWeek/opengl.csv',
  react: '/queries/topicsPerWeek/react.csv',
  rust: '/queries/topicsPerWeek/rust.csv',
  sencha: '/queries/topicsPerWeek/sencha.csv',
  sprout: '/queries/topicsPerWeek/sprout.csv',
  webgl: '/queries/topicsPerWeek/webgl.csv'
};
